# /tests/conftest.py
"""
Helper script that contains the complete list of fixtures that were made globally available to pytest for testing the
scholar_flux package. The test suite fixtures are prepared to aid the testing of both simulated and known provider
configurations.
"""

from tests.fixtures.plos_api import (
    plos_search_api,
    plos_coordinator,
    plos_page_1_url,
    plos_page_1_data,
    plos_page_2_url,
    plos_page_2_data,
    plos_headers,
    plos_page_1_response,
    plos_page_2_response,
)

from tests.fixtures.pubmed_api import (
    mock_pubmed_search_json_path,
    mock_pubmed_fetch_json_path,
    mock_pubmed_search_data,
    mock_pubmed_fetch_data,
    mock_pubmed_search_endpoint,
    mock_pubmed_fetch_endpoint,
    mock_pubmed_search_response,
    mock_pubmed_fetch_response,
)

from tests.fixtures.api_parameter_config import default_api_parameter_map, default_api_parameter_config

from tests.fixtures.config import (
    scholar_flux_logger,
    original_config_test_api_key,
    new_config_test_api_key,
    original_config,
    new_config,
    original_api_parameter_config,
    new_api_parameter_config,
    core_api_key,
    pubmed_api_key,
    springer_nature_api_key,
    crossref_api_key,
)

from tests.fixtures.response_simulation import (
    mock_response,
    mock_cache_storage_data,
    mock_successful_response,
    mock_internal_error_response,
    mock_unauthorized_response,
    mock_rate_limit_exceeded_response,
    mock_academic_json_path,
    mock_academic_json,
    academic_json_response,
    mock_academic_yaml_path,
    mock_academic_yaml,
    academic_yaml_response,
)
from tests.fixtures.cleanup_utils import cleanup
from tests.fixtures.package_dependencies import (
    redis_dependency,
    mongodb_dependency,
    sqlalchemy_dependency,
    db_dependency_unavailable,
    xml_parsing_dependency,
    yaml_parsing_dependency,
    session_encryption_dependency,
)

from tests.fixtures.jsons import sample_json, mock_api_parsed_json_records

from tests.fixtures.mock_cache_session import (
    default_cache_session_manager,
    default_cache_session,
    default_seconds_cache_expiration,
    default_backend,
    default_cache_filename,
    default_cache_directory,
    default_memory_cache_session_manager,
    default_memory_cache_session,
    default_encryption_cache_session,
    default_secret_salt,
    default_secret_key,
    default_encryption_cache_session_manager,
    default_encryption_cache_filename,
    default_encryption_serializer_pipeline,
    incorrect_secret_key,
    incorrect_secret_salt,
    incorrect_secret_salt_encryption_cache_session_manager,
    sqlite_db_url,
)

from tests.fixtures.data_storage_classes import (
    redis_test_config,
    storage_test_namespace,
    mongo_test_config,
    sqlite_test_config,
    redis_test_storage,
    mongo_test_storage,
    mongo_nm_test_storage,
    sqlite_test_storage,
    sqlite_nm_test_storage,
    in_memory_test_storage,
    in_memory_nm_test_storage,
    null_test_storage,
)


__all__ = [
    "plos_search_api",
    "plos_coordinator",
    "plos_page_1_url",
    "plos_page_1_data",
    "plos_page_2_url",
    "plos_page_2_data",
    "plos_headers",
    "plos_page_1_response",
    "plos_page_2_response",
    "scholar_flux_logger",
    "original_config_test_api_key",
    "new_config_test_api_key",
    "original_config",
    "new_config",
    "original_api_parameter_config",
    "new_api_parameter_config",
    "core_api_key",
    "pubmed_api_key",
    "mock_response",
    "mock_cache_storage_data",
    "mock_pubmed_search_json_path",
    "mock_pubmed_fetch_json_path",
    "mock_successful_response",
    "mock_internal_error_response",
    "mock_unauthorized_response",
    "mock_rate_limit_exceeded_response",
    "mock_academic_json_path",
    "mock_academic_json",
    "academic_json_response",
    "mock_academic_yaml_path",
    "mock_academic_yaml",
    "academic_yaml_response",
    "mock_pubmed_search_data",
    "mock_pubmed_fetch_data",
    "mock_pubmed_search_endpoint",
    "mock_pubmed_fetch_endpoint",
    "mock_pubmed_search_response",
    "mock_pubmed_fetch_response",
    "cleanup",
    "sample_json",
    "mock_api_parsed_json_records",
    "default_api_parameter_map",
    "default_api_parameter_config",
    "redis_dependency",
    "mongodb_dependency",
    "sqlalchemy_dependency",
    "xml_parsing_dependency",
    "yaml_parsing_dependency",
    "session_encryption_dependency",
    "db_dependency_unavailable",
    "default_cache_session_manager",
    "default_cache_session",
    "default_seconds_cache_expiration",
    "default_backend",
    "default_cache_filename",
    "default_cache_directory",
    "default_memory_cache_session_manager",
    "default_memory_cache_session",
    "default_encryption_cache_session",
    "default_secret_salt",
    "default_secret_key",
    "default_encryption_cache_session_manager",
    "default_encryption_cache_filename",
    "default_encryption_serializer_pipeline",
    "incorrect_secret_key",
    "incorrect_secret_salt",
    "incorrect_secret_salt_encryption_cache_session_manager",
    "sqlite_db_url",
    "core_api_key",
    "pubmed_api_key",
    "springer_nature_api_key",
    "crossref_api_key",
    "redis_test_config",
    "storage_test_namespace",
    "mongo_test_config",
    "sqlite_test_config",
    "redis_test_storage",
    "mongo_test_storage",
    "mongo_nm_test_storage",
    "sqlite_test_storage",
    "sqlite_nm_test_storage",
    "in_memory_test_storage",
    "in_memory_nm_test_storage",
    "null_test_storage",
]
